variable "region" {}
variable "vpc_cidr" {}
variable "environment" {}
variable "public_subnets_cidr" {}
variable "availability_zones" {}
variable "private_subnets_cidr" {}
variable "key_name" {}
variable "private_ips" {}
variable "instance_type" {}
